name: Welcome

on:
  push:
    branches:
      - main

jobs:
  usingubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Welcome
      run: echo "Welcome everyone"